// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReflowOven.Infrastructure.Persistence;

#nullable disable

namespace ReflowOven.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReflowDbContext))]
    [Migration("20260604191923_AddCreatedBy")]
    partial class AddCreatedBy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReflowOven.Domain.Entities.Board", b =>
                {
                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<int>("Hours")
                        .HasColumnType("integer");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Role");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.Calibration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<double>("CurrentGain")
                        .HasColumnType("double precision");

                    b.Property<double>("CurrentOffset")
                        .HasColumnType("double precision");

                    b.Property<int>("FanPwmMax")
                        .HasColumnType("integer");

                    b.Property<int>("FanPwmMin")
                        .HasColumnType("integer");

                    b.Property<double>("ThermoOffset")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Calibrations", t =>
                        {
                            t.HasCheckConstraint("CK_Calibration_SingleRow", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.ChangeLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("ConfigBullets")
                        .HasColumnType("text[]");

                    b.Property<string>("DetailKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProgramId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("Changes");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.DeviceInfo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("BackendVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoardIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HtmlVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("StorageFreeGB")
                        .HasColumnType("double precision");

                    b.Property<double>("StorageTotalGB")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("DeviceInfo", t =>
                        {
                            t.HasCheckConstraint("CK_DeviceInfo_SingleRow", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.ErrorLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultTypeCode")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<int>("InputVoltage")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OutputVoltage")
                        .HasColumnType("integer");

                    b.Property<int>("OvenTemp")
                        .HasColumnType("integer");

                    b.Property<int>("PcbTemp")
                        .HasColumnType("integer");

                    b.Property<string>("ProgramId")
                        .HasColumnType("text");

                    b.Property<string>("ProgramName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("FaultTypeCode");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.ExecutionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("FaultAtT")
                        .HasColumnType("integer");

                    b.Property<int?>("FaultAtTemp")
                        .HasColumnType("integer");

                    b.Property<string>("FaultTypeCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("LinkedErrorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PeakCurrent")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<int>("PeakTemp")
                        .HasColumnType("integer");

                    b.Property<string>("ProgramId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("LinkedErrorId");

                    b.HasIndex("StartedAt");

                    b.ToTable("Executions");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.FaultType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("FaultTypes");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.FavoriteProgram", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProgramId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("UserId", "ProgramId");

                    b.HasIndex("ProgramId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.LogEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ErrorLogEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExecutionReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ErrorLogEntryId");

                    b.HasIndex("ExecutionReportId");

                    b.ToTable("LogEvents");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Read");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.NotificationSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Alert")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Buzzer")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Process")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SettingsId")
                        .HasColumnType("integer");

                    b.Property<string>("Sound")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SettingsId");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.OperationLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("Category");

                    b.HasIndex("Object");

                    b.HasIndex("Type");

                    b.ToTable("OperationLog");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.ReflowProgram", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Description")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastUsed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("RunCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.RunSeriesPreference", b =>
                {
                    b.Property<int>("SettingsId")
                        .HasColumnType("integer");

                    b.Property<string>("Signal")
                        .HasColumnType("text");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("SettingsId", "Signal");

                    b.ToTable("RunSeriesPreferences");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.Settings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Settings", t =>
                        {
                            t.HasCheckConstraint("CK_Settings_SingleRow", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.SystemLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("SystemLog");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastPasswordReminderAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LoginCount")
                        .HasColumnType("bigint");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("PasswordIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Name", "\"Name\" ~ '^[[:alnum:].]+$'");
                        });
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.UserActivityStat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Label")
                        .IsUnique();

                    b.ToTable("UserActivityStats");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.ChangeLogEntry", b =>
                {
                    b.OwnsMany("ReflowOven.Domain.Entities.ChangePointRow", "Points", b1 =>
                        {
                            b1.Property<Guid>("ChangeLogEntryId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Index");

                            b1.Property<int>("Ramp");

                            b1.Property<int>("Role");

                            b1.Property<int>("Temp");

                            b1.Property<int>("TimeSec");

                            b1.HasKey("ChangeLogEntryId", "__synthesizedOrdinal");

                            b1.ToTable("Changes");

                            b1
                                .ToJson("Points")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChangeLogEntryId");
                        });

                    b.Navigation("Points");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.DeviceInfo", b =>
                {
                    b.OwnsOne("ReflowOven.Domain.Entities.OsInfo", "Os", b1 =>
                        {
                            b1.Property<int>("DeviceInfoId")
                                .HasColumnType("integer");

                            b1.Property<string>("Kernel")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DeviceInfoId");

                            b1.ToTable("DeviceInfo");

                            b1.WithOwner()
                                .HasForeignKey("DeviceInfoId");
                        });

                    b.Navigation("Os")
                        .IsRequired();
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.ErrorLogEntry", b =>
                {
                    b.HasOne("ReflowOven.Domain.Entities.FaultType", "FaultType")
                        .WithMany("Errors")
                        .HasForeignKey("FaultTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ReflowOven.Domain.Entities.FailureSnapshot", "Snapshot", b1 =>
                        {
                            b1.Property<Guid>("ErrorLogEntryId");

                            b1.Property<int>("DurationSec");

                            b1.HasKey("ErrorLogEntryId");

                            b1.ToTable("Errors");

                            b1
                                .ToJson("Snapshot")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ErrorLogEntryId");

                            b1.OwnsMany("ReflowOven.Domain.Entities.SnapshotSeries", "Series", b2 =>
                                {
                                    b2.Property<Guid>("FailureSnapshotErrorLogEntryId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Color")
                                        .IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("Unit")
                                        .IsRequired();

                                    b2.PrimitiveCollection<string>("Values")
                                        .IsRequired();

                                    b2.HasKey("FailureSnapshotErrorLogEntryId", "__synthesizedOrdinal");

                                    b2.ToTable("Errors");

                                    b2.WithOwner()
                                        .HasForeignKey("FailureSnapshotErrorLogEntryId");
                                });

                            b1.Navigation("Series");
                        });

                    b.Navigation("FaultType");

                    b.Navigation("Snapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.ExecutionReport", b =>
                {
                    b.OwnsMany("ReflowOven.Domain.Entities.ExecProfilePoint", "Points", b1 =>
                        {
                            b1.Property<Guid>("ExecutionReportId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Kind");

                            b1.Property<int>("T");

                            b1.Property<int>("Temp");

                            b1.HasKey("ExecutionReportId", "__synthesizedOrdinal");

                            b1.ToTable("Executions");

                            b1
                                .ToJson("Points")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionReportId");
                        });

                    b.OwnsOne("ReflowOven.Domain.Entities.FailureSnapshot", "Trace", b1 =>
                        {
                            b1.Property<Guid>("ExecutionReportId");

                            b1.Property<int>("DurationSec");

                            b1.HasKey("ExecutionReportId");

                            b1.ToTable("Executions");

                            b1
                                .ToJson("Trace")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionReportId");

                            b1.OwnsMany("ReflowOven.Domain.Entities.SnapshotSeries", "Series", b2 =>
                                {
                                    b2.Property<Guid>("FailureSnapshotExecutionReportId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Color")
                                        .IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("Unit")
                                        .IsRequired();

                                    b2.PrimitiveCollection<string>("Values")
                                        .IsRequired();

                                    b2.HasKey("FailureSnapshotExecutionReportId", "__synthesizedOrdinal");

                                    b2.ToTable("Executions");

                                    b2.WithOwner()
                                        .HasForeignKey("FailureSnapshotExecutionReportId");
                                });

                            b1.Navigation("Series");
                        });

                    b.OwnsMany("ReflowOven.Domain.Entities.ProfileComparisonRow", "Comparison", b1 =>
                        {
                            b1.Property<Guid>("ExecutionReportId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("StageIndex");

                            b1.Property<int>("TempProg");

                            b1.Property<int>("TempReal");

                            b1.Property<int>("TimeProgSeconds");

                            b1.Property<int>("TimeRealSeconds");

                            b1.HasKey("ExecutionReportId", "__synthesizedOrdinal");

                            b1.ToTable("Executions");

                            b1
                                .ToJson("Comparison")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionReportId");
                        });

                    b.Navigation("Comparison");

                    b.Navigation("Points");

                    b.Navigation("Trace")
                        .IsRequired();
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.FavoriteProgram", b =>
                {
                    b.HasOne("ReflowOven.Domain.Entities.ReflowProgram", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReflowOven.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.LogEvent", b =>
                {
                    b.HasOne("ReflowOven.Domain.Entities.ErrorLogEntry", "ErrorLogEntry")
                        .WithMany("Events")
                        .HasForeignKey("ErrorLogEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ReflowOven.Domain.Entities.ExecutionReport", "ExecutionReport")
                        .WithMany("Events")
                        .HasForeignKey("ExecutionReportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ErrorLogEntry");

                    b.Navigation("ExecutionReport");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.NotificationSetting", b =>
                {
                    b.HasOne("ReflowOven.Domain.Entities.Settings", null)
                        .WithMany("Notifications")
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.OperationLogEntry", b =>
                {
                    b.OwnsMany("ReflowOven.Domain.Entities.OperationField", "Data", b1 =>
                        {
                            b1.Property<Guid>("OperationLogEntryId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("After");

                            b1.Property<string>("Before");

                            b1.Property<string>("Field")
                                .IsRequired();

                            b1.HasKey("OperationLogEntryId", "__synthesizedOrdinal");

                            b1.ToTable("OperationLog");

                            b1
                                .ToJson("Data")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("OperationLogEntryId");
                        });

                    b.Navigation("Data");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("ReflowOven.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.ReflowProgram", b =>
                {
                    b.OwnsMany("ReflowOven.Domain.Entities.ProfilePoint", "Profile", b1 =>
                        {
                            b1.Property<string>("ReflowProgramId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<double>("T");

                            b1.Property<double>("Temp");

                            b1.HasKey("ReflowProgramId", "__synthesizedOrdinal");

                            b1.ToTable("Programs");

                            b1
                                .ToJson("Profile")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ReflowProgramId");
                        });

                    b.OwnsMany("ReflowOven.Domain.Entities.ProfileSegment", "Segments", b1 =>
                        {
                            b1.Property<string>("ReflowProgramId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("DurationSec");

                            b1.Property<int>("Ramp");

                            b1.Property<int>("Temp");

                            b1.HasKey("ReflowProgramId", "__synthesizedOrdinal");

                            b1.ToTable("Programs");

                            b1
                                .ToJson("Segments")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ReflowProgramId");
                        });

                    b.Navigation("Profile");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.RunSeriesPreference", b =>
                {
                    b.HasOne("ReflowOven.Domain.Entities.Settings", null)
                        .WithMany("RunSeries")
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.Settings", b =>
                {
                    b.OwnsOne("ReflowOven.Domain.Entities.NetworkConfig", "Network", b1 =>
                        {
                            b1.Property<int>("SettingsId")
                                .HasColumnType("integer");

                            b1.Property<string>("DnsPrimary")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)");

                            b1.Property<string>("DnsSecondary")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)");

                            b1.Property<string>("Gateway")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)");

                            b1.Property<string>("Ip")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)");

                            b1.Property<string>("Mask")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)");

                            b1.Property<bool>("StaticIp")
                                .HasColumnType("boolean");

                            b1.HasKey("SettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingsId");
                        });

                    b.OwnsOne("ReflowOven.Domain.Entities.OvenLimits", "Oven", b1 =>
                        {
                            b1.Property<int>("SettingsId")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxFanRpm")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxTemp")
                                .HasColumnType("integer");

                            b1.HasKey("SettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingsId");
                        });

                    b.OwnsOne("ReflowOven.Domain.Entities.PidGains", "Pid", b1 =>
                        {
                            b1.Property<int>("SettingsId")
                                .HasColumnType("integer");

                            b1.Property<double>("D")
                                .HasColumnType("double precision");

                            b1.Property<double>("I")
                                .HasColumnType("double precision");

                            b1.Property<double>("P")
                                .HasColumnType("double precision");

                            b1.HasKey("SettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingsId");
                        });

                    b.OwnsOne("ReflowOven.Domain.Entities.ProcessConfig", "Process", b1 =>
                        {
                            b1.Property<int>("SettingsId")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxExtraTimeSec")
                                .HasColumnType("integer");

                            b1.HasKey("SettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingsId");
                        });

                    b.OwnsOne("ReflowOven.Domain.Entities.VoltageThresholds", "Voltage", b1 =>
                        {
                            b1.Property<int>("SettingsId")
                                .HasColumnType("integer");

                            b1.Property<int>("Max")
                                .HasColumnType("integer");

                            b1.Property<int>("Min")
                                .HasColumnType("integer");

                            b1.HasKey("SettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingsId");
                        });

                    b.Navigation("Network")
                        .IsRequired();

                    b.Navigation("Oven")
                        .IsRequired();

                    b.Navigation("Pid")
                        .IsRequired();

                    b.Navigation("Process")
                        .IsRequired();

                    b.Navigation("Voltage")
                        .IsRequired();
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.User", b =>
                {
                    b.OwnsOne("ReflowOven.Domain.Entities.UserPreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("UserId");

                            b1.Property<bool>("Alvo");

                            b1.Property<bool>("Board");

                            b1.Property<bool>("BoardFan");

                            b1.Property<bool>("Current");

                            b1.Property<bool>("Oven");

                            b1.Property<bool>("OvenFan");

                            b1.Property<int>("Theme");

                            b1.Property<bool>("Voltage");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1
                                .ToJson("Preferences")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.UserActivityStat", b =>
                {
                    b.HasOne("ReflowOven.Domain.Entities.User", "User")
                        .WithMany("ActivityStats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.ErrorLogEntry", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.ExecutionReport", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.FaultType", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.Settings", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("RunSeries");
                });

            modelBuilder.Entity("ReflowOven.Domain.Entities.User", b =>
                {
                    b.Navigation("ActivityStats");
                });
#pragma warning restore 612, 618
        }
    }
}
